version: '3.8'

services:
  middleware:
    build:
      context: .
      dockerfile: Dockerfile.middleware
    container_name: middleware-service
    ports:
      - "4000:4000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]  # Ensure middleware is up
      interval: 5s
      timeout: 3s
      retries: 5
    

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-service
    ports:
      - "3000:3000"
      - "6006:6006"
    depends_on:
      middleware:  # Ensures middleware builds first
        condition: service_healthy
    networks:
      - app-network
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh middleware-service 4000"]

networks:
  app-network:
    driver: bridge

 